### ISSUE TITLE
Может SSH ключ генерировать и сохранять в lockbox? 

### ISSUE THREAD

**Issue by patsevanton** [terraform-yacloud-modules/terraform-yandex-instance-group#48]
Я правильно понимаю что сертификат генерируется в terraform https://github.com/terraform-yacloud-modules/terraform-yandex-instance-group/blob/main/main.tf#L13 

Может SSH ключ генерировать и сохранять в lockbox?

**Comment by kvendingoldo** [comment]
@patsevanton все верно. У меня в проекте я так и делаю - забираю из аутпута модуля сертификаты и кладу в Я через lockbox модуль. Давай я завтра добавлю пример

**Comment by patsevanton** [comment]
@kvendingoldo получилось найти пример?

**Comment by kvendingoldo** [comment]
Да, скоро кину ПР

**Comment by kvendingoldo** [comment]
@patsevanton глянь пожалуйста
https://github.com/terraform-yacloud-modules/terraform-yandex-instance-group/pull/53

**Comment by patsevanton** [comment]
https://github.com/terraform-yacloud-modules/terraform-yandex-instance-group/pull/54
